FROM alpine:3.13

RUN echo http://mirrors.aliyun.com/alpine/v3.13/main/ > /etc/apk/repositories && \
    echo http://mirrors.aliyun.com/alpine/v3.13/community/ >> /etc/apk/repositories
RUN apk update && apk upgrade

RUN apk add --no-cache bash freetype wine && \
	rm -fr /var/cache/apk/*

ENV LANGUAGE=zh_CN.UTF-8 \
    LC_ALL=zh_CN.UTF-8 \
    LANG=zh_CN.UTF-8 \
    TZ=UTC-8
    
ENTRYPOINT ["wine64"]
